
SCREEN_SIZE = WIDTH, HEIGHT = 480, 720

OUTLINE_SIZE = 2
OUTLINE_BORDER_RADIUS = 5

INNER_BORDER_RADIUS = 2

GAME_AREA_OFFSET = 50

BLOCK_SIZE = BLOCK_WIDTH, BLOCK_HEIGHT = 35, 35
START_POS = WIDTH / 2, 50

speed = [0, BLOCK_SIZE[0]]